import type { StoryTemplateConfig } from '@/types/story-template';

// Template 1 — Classic: reproduz exatamente o layout hardcoded atual (full_text_block)
const classicTemplate: StoryTemplateConfig = {
  version: 1,
  canvasWidth: 1080,
  canvasHeight: 1920,
  accentColor: '#FF6B00',
  layers: [
    {
      id: 'bg-blur',
      type: 'background_blur',
      label: 'Fundo desfocado',
      visible: true,
      opacity: 1,
      blurRadius: 12,
      brightness: 0.4,
    },
    {
      id: 'hero-image',
      type: 'image',
      label: 'Imagem principal',
      visible: true,
      opacity: 1,
      source: 'cover',
      x: 0,
      y: 0,
      width: 1080,
      height: 1150,
      fit: 'cover',
      position: 'top',
    },
    {
      id: 'gradient-overlay',
      type: 'gradient',
      label: 'Gradiente',
      visible: true,
      opacity: 1,
      x: 0,
      y: 550,
      width: 1080,
      height: 1370,
      direction: 'to-bottom',
      stops: [
        { offset: 0, color: '#000000', opacity: 0 },
        { offset: 0.35, color: '#000000', opacity: 0.65 },
        { offset: 1, color: '#000000', opacity: 0.97 },
      ],
    },
    {
      id: 'text-block',
      type: 'text',
      label: 'Bloco de texto',
      visible: true,
      opacity: 1,
      source: 'full_text_block',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      fontSize: 56,
      fontWeight: 700,
      color: '#FFFFFF',
      lineHeight: 1.25,
    },
  ],
};

// Template 2 — Text-First: texto no topo, imagem na metade inferior
const textFirstTemplate: StoryTemplateConfig = {
  version: 1,
  canvasWidth: 1080,
  canvasHeight: 1920,
  accentColor: '#FF6B00',
  layers: [
    {
      id: 'bg-blur',
      type: 'background_blur',
      label: 'Fundo desfocado',
      visible: true,
      opacity: 1,
      blurRadius: 18,
      brightness: 0.3,
    },
    {
      id: 'bg-gradient',
      type: 'gradient',
      label: 'Overlay escuro',
      visible: true,
      opacity: 1,
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      direction: 'to-bottom',
      stops: [
        { offset: 0, color: '#000000', opacity: 0.2 },
        { offset: 1, color: '#000000', opacity: 0.85 },
      ],
    },
    {
      id: 'chip',
      type: 'text',
      label: 'Chip de categoria',
      visible: true,
      opacity: 1,
      source: 'niche_label',
      x: 72,
      y: 160,
      width: 600,
      height: 60,
      fontSize: 20,
      fontWeight: 700,
      color: '#FFFFFF',
      lineHeight: 1,
      backgroundColor: '#FF6B00',
      borderRadius: 4,
      paddingX: 16,
      paddingY: 8,
      alignSelf: 'flex-start',
    },
    {
      id: 'title',
      type: 'text',
      label: 'Título',
      visible: true,
      opacity: 1,
      source: 'title',
      x: 72,
      y: 260,
      width: 936,
      height: 400,
      fontSize: 64,
      fontWeight: 700,
      color: '#FFFFFF',
      lineHeight: 1.2,
      truncateAt: 70,
    },
    {
      id: 'divider',
      type: 'shape',
      label: 'Divisor',
      visible: true,
      opacity: 1,
      shape: 'rectangle',
      x: 72,
      y: 700,
      width: 80,
      height: 3,
      backgroundColor: '#FF6B00',
      borderRadius: 2,
    },
    {
      id: 'summary',
      type: 'text',
      label: 'Resumo',
      visible: true,
      opacity: 1,
      source: 'summary',
      x: 72,
      y: 730,
      width: 936,
      height: 280,
      fontSize: 32,
      fontWeight: 400,
      color: '#D0D0D0',
      lineHeight: 1.55,
      truncateAt: 200,
    },
    {
      id: 'hero-image',
      type: 'image',
      label: 'Imagem',
      visible: true,
      opacity: 1,
      source: 'cover',
      x: 0,
      y: 1060,
      width: 1080,
      height: 860,
      fit: 'cover',
      position: 'center',
    },
    {
      id: 'source-name',
      type: 'text',
      label: 'Fonte',
      visible: true,
      opacity: 1,
      source: 'source_name',
      x: 72,
      y: 1860,
      width: 936,
      height: 40,
      fontSize: 22,
      fontWeight: 400,
      color: 'rgba(255,255,255,0.55)',
      lineHeight: 1,
    },
    {
      id: 'accent-bar',
      type: 'shape',
      label: 'Barra de acento',
      visible: true,
      opacity: 1,
      shape: 'rectangle',
      x: 0,
      y: 0,
      width: 'full',
      height: 8,
      backgroundColor: '#FF6B00',
      anchor: 'absolute',
      bottom: 0,
      left: 0,
    },
  ],
};

// Template 3 — Minimal: full-bleed, título grande + barra laranja
const minimalTemplate: StoryTemplateConfig = {
  version: 1,
  canvasWidth: 1080,
  canvasHeight: 1920,
  accentColor: '#FF6B00',
  layers: [
    {
      id: 'bg-blur',
      type: 'background_blur',
      label: 'Fundo desfocado',
      visible: true,
      opacity: 1,
      blurRadius: 8,
      brightness: 0.5,
    },
    {
      id: 'full-image',
      type: 'image',
      label: 'Imagem full-bleed',
      visible: true,
      opacity: 1,
      source: 'cover',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      fit: 'cover',
      position: 'center',
    },
    {
      id: 'gradient-overlay',
      type: 'gradient',
      label: 'Gradiente inferior',
      visible: true,
      opacity: 1,
      x: 0,
      y: 900,
      width: 1080,
      height: 1020,
      direction: 'to-bottom',
      stops: [
        { offset: 0, color: '#000000', opacity: 0 },
        { offset: 0.4, color: '#000000', opacity: 0.7 },
        { offset: 1, color: '#000000', opacity: 0.95 },
      ],
    },
    {
      id: 'title',
      type: 'text',
      label: 'Título',
      visible: true,
      opacity: 1,
      source: 'title',
      x: 72,
      y: 1180,
      width: 936,
      height: 500,
      fontSize: 72,
      fontWeight: 700,
      color: '#FFFFFF',
      lineHeight: 1.2,
      truncateAt: 60,
    },
    {
      id: 'accent-bar',
      type: 'shape',
      label: 'Barra de acento',
      visible: true,
      opacity: 1,
      shape: 'rectangle',
      x: 0,
      y: 0,
      width: 'full',
      height: 8,
      backgroundColor: '#FF6B00',
      anchor: 'absolute',
      bottom: 0,
      left: 0,
    },
  ],
};

export interface DefaultTemplateEntry {
  slot: 1 | 2 | 3;
  name: string;
  config: StoryTemplateConfig;
}

export const DEFAULT_TEMPLATES_PER_NICHE: DefaultTemplateEntry[] = [
  { slot: 1, name: 'Classic', config: classicTemplate },
  { slot: 2, name: 'Text-First', config: textFirstTemplate },
  { slot: 3, name: 'Minimal', config: minimalTemplate },
];
